config/routes.rb
Ptonfml::Application.routes.draw do
  resources :posts, except: :new

  match 'posts/sms', to: 'posts#sms', via: 'post'

  match 'liked', to: 'posts#liked', as: :most_liked
  match 'disliked', to: 'posts#disliked', as: :most_disliked

  match 'search', to: 'posts#search', as: :search

  resources :comments, only: [:create, :destroy]

  match 'review', to: 'posts#review', as: :review

  match 'posts/:id/approve', to: 'posts#approve', via: 'put', as: :approve_post
  match 'posts/:id/disapprove', to: 'posts#disapprove', via: 'put', as: :disapprove_post

  match 'posts/upvote', to: 'posts#upvote', via: 'post'
  match 'posts/downvote', to: 'posts#downvote', via: 'post'

  root to: 'posts#index'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  body             :text(255)
#  commentable_id   :integer
#  commentable_type :string(255)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#  ip               :string(255)
#

class Comment < ActiveRecord::Base
  attr_accessible :name, :body
  validates :name, presence: true, length: { minimum: 1 }
  validates :body, presence: true, length: { minimum: 1 }

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  default_scope order: 'comments.created_at ASC'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :get_parent, only: :create

  # POST /comments
  def create
    @comment = @parent.comments.build(params[:comment])

    # Use default name if none
    if @comment.name.length == 0
      @comment.name = "Anonymous"
    end

    # Make sure only admins can use admin names
    if not is_admin?
      if @comment.name == 'The Giant Peach'
        @comment.name = 'Hall of Shame'
      elsif @comment.name == 'A Boy Named James'
        @comment.name = "Hall of Lame"
      end
    end

    # Set IP address
    @comment.ip = request.remote_ip

    if @comment.save
      render partial: 'comment', locals: { comment: @comment }
    else
      render nothing: true
    end
  end

  # DELETE /comments/1
  def destroy
    if session[:admin]
      @comment = Comment.find(params[:id])
      @comment.destroy
    end

    redirect_to root_url
  end

  def get_parent
    parent_id = params[:parent_id]
    parent_type = params[:parent_type]

    if parent_type == 'post'
      @parent = Post.find_by_id(parent_id)
    elsif parent_type == 'comment'
      @parent = Comment.find_by_id(parent_id)
    end

    redirect_to root_url if @parent.nil?
  end
end

app/views/comments/_comment.html.erb
<li class="comment-container" data-target="<%= comment.id %>">
  <div class="comment">
    <% if is_admin? %>
      <%= link_to 'x', comment_path(comment),
          method: :delete,
          confirm: 'Are you sure?',
          class: 'close' %>
    <% end %>
    <span class="name <%= 'mod' if admin_names.include? comment.name %>">
      <strong><%= comment.name %></strong>
    </span>
    <span class="timestamp">
      <%= time_ago_in_words comment.created_at %> ago
    </span>
    <a class="comment-comment pull-right">Reply</a>
    <div class="body">
      <%= simple_format auto_link h comment.body %>
    </div>
  </div>
  <ul class="comments">
  <% unless comment.comments.empty? %>
    <%= render partial: 'comments/comment', collection: comment.comments %>
  <% end %>
  </ul>
</li>

app/views/comments/_form.html.erb
  <%= form_for Comment.new, html: { class: 'comment-form form-horizontal well' } do |f| %>
  <input name="parent_id" type="hidden" value="">
  <input name="parent_type" type="hidden" value="">
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, class: 'name-field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, 'Comment', class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 2, class: 'comment-field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Submit", class: "btn btn-primary submit-comment" %>
    <button class="btn cancel-comment">Cancel</button>
  </div>
  <% end %>