config/routes.rb
Ptonfml::Application.routes.draw do
  resources :posts, except: :new

  match 'posts/sms', to: 'posts#sms', via: 'post'

  match 'liked', to: 'posts#liked', as: :most_liked
  match 'disliked', to: 'posts#disliked', as: :most_disliked

  match 'search', to: 'posts#search', as: :search

  resources :comments, only: [:create, :destroy]

  match 'review', to: 'posts#review', as: :review

  match 'posts/:id/approve', to: 'posts#approve', via: 'put', as: :approve_post
  match 'posts/:id/disapprove', to: 'posts#disapprove', via: 'put', as: :disapprove_post

  match 'posts/upvote', to: 'posts#upvote', via: 'post'
  match 'posts/downvote', to: 'posts#downvote', via: 'post'

  root to: 'posts#index'

end

app/views/fmls/_fml.html.erb
<div class="post span8 well" data-target="<%= fml.id %>">
  <div class="row">
    <% has_image = !fml.image_file_name.blank? %>
    <div class="span6 left">
      <div class="content well <%= 'center' if has_image %> <%= 'mod' if fml.admin %>">
        <%= image_tag fml.image.url(:original), class: 'image' if has_image %>
        <%= simple_format auto_link h fml.content %>
      </div>
    </div>
    <div class="span2">
      <div class="meta center">
        <%= link_to fml.created_at.strftime("%I:%M%p on %m/%d/%Y"), post_path(fml), class: 'timestamp' %>
        <div class="vote">
          <a class="like btn btn-success <%= 'disabled' if @votes and @votes.include? fml.id %>">
            <span class="count"><%= fml.likes %></span>
            <i class="icon-thumbs-up"></i>
          </a>
          <a class="dislike btn btn-danger <%= 'disabled' if @votes and @votes.include? fml.id %>">
            <span class="count"><%= fml.dislikes %></span>
            <i class="icon-thumbs-down"></i>
          </a>
        </div>
        <div class="fb-like">
          <iframe src="//www.facebook.com/plugins/like.php?href=<%= u post_url(fml) %>&amp;send=false&amp;layout=button_count&amp;width=80&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=480322535317003" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:80px; height:21px;" allowTransparency="true"></iframe>
        </div>
        <%= link_to 'Post Comment', '#', class: 'post-comment' %>
      </div>
    </div>
  </div>

  <ul class="comments">
    <% unless fml.comments.empty? %>
      <%= render partial: 'comments/comment', collection: fml.comments %>
    <% end %>
  </ul>
</div>

app/views/fmls/_form.html.erb
<%= form_for post, html: { multipart: true } do |f| %>
  <%= f.hidden_field :type, value: 'FML' %>
  <%= f.label :image, 'Image optional', class: 'image-label' %>
  <%= f.file_field :image %>
  <%= f.text_area :content, rows: 4 %>
  <%= f.submit "Submit FML", class: "submit-button btn btn-primary btn-large" %>
<% end %>