config/routes.rb
Ptonfml::Application.routes.draw do
  resources :posts, except: :new

  match 'posts/sms', to: 'posts#sms', via: 'post'

  match 'liked', to: 'posts#liked', as: :most_liked
  match 'disliked', to: 'posts#disliked', as: :most_disliked

  match 'search', to: 'posts#search', as: :search

  resources :comments, only: [:create, :destroy]

  match 'review', to: 'posts#review', as: :review

  match 'posts/:id/approve', to: 'posts#approve', via: 'put', as: :approve_post
  match 'posts/:id/disapprove', to: 'posts#disapprove', via: 'put', as: :disapprove_post

  match 'posts/upvote', to: 'posts#upvote', via: 'post'
  match 'posts/downvote', to: 'posts#downvote', via: 'post'

  root to: 'posts#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                 :integer         not null, primary key
#  content            :text
#  likes              :integer         default(0)
#  dislikes           :integer         default(0)
#  approved           :boolean         default(FALSE)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  ip                 :string(255)
#  admin              :boolean         default(FALSE)
#  type               :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  reviewed           :boolean         default(FALSE)
#  phone              :string(255)
#

class Post < ActiveRecord::Base
  attr_accessible :admin, :type, :image

  # Type validation
  validates :type, presence: true

  # Comments
  has_many :comments, as: :commentable, dependent: :destroy

  # Image
  has_attached_file :image, styles: { original: "500x500>" },
  storage: :s3,
  bucket: ENV['S3_BUCKET_NAME'],
  s3_credentials: {
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  def to_param
    words = content.split(' ')
    words_in_preview = [words.length, 7].min
    preview = words[0..(words_in_preview - 1)].join(' ').parameterize
    "#{id}-#{preview}"
  end

  scope :approved, where(approved: true)
  scope :unreviewed, where(reviewed: false)
  scope :recent, order: 'posts.created_at DESC'
  scope :most_liked, order: 'posts.likes DESC'
  scope :most_disliked, order: 'posts.dislikes DESC'

  # Make STI children use Post routes and controller
  def self.inherited(child)
    child.instance_eval do
      def model_name
        Post.model_name
      end
    end
    super
  end
end

class FML < Post
  attr_accessible :content

  validates :content, presence: true
end

class Meme < Post
  validates_attachment :image, presence: true, size: { in: 0..4.megabytes }

  def to_param
    id
  end
end

class GIF < Post
  attr_accessible :content

  validates :content, presence: true
  validates_attachment :image, presence: true, size: { in: 0..4.megabytes }
  validates :image, attachment_content_type: { content_type: 'image/gif' }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_as_admin, only: :review
  before_filter :authenticate, only: :review
  skip_before_filter :verify_authenticity_token, only: :sms

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.new
    @posts = Post.approved.recent.paginate(page: params[:page], per_page: 20)

    @votes = session[:votes]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def liked
    @post = Post.new
    @posts = Post.approved.most_liked.paginate(page: params[:page], per_page: 20)

    @votes = session[:votes]

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @posts }
    end
  end

  def disliked
    @post = Post.new
    @posts = Post.approved.most_disliked.paginate(page: params[:page], per_page: 20)

    @votes = session[:votes]

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @posts }
    end
  end

  def search
    @post = Post.new
    @posts = Post.approved.where("LOWER(content) LIKE ?", '%' + params[:query].downcase + '%').recent.paginate(page: params[:page], per_page: 20)

    @votes = session[:votes]

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @posts }
    end
  end

  def review
    if params[:view] == 'approved'
      @posts = Post.approved.recent.paginate(page: params[:page], per_page: 20)
    elsif params[:view] == 'disapproved'
      @posts = Post.where(approved: false).recent.paginate(page: params[:page], per_page: 20)
    else
      @posts = Post.unreviewed.recent.paginate(page: params[:page], per_page: 20)
    end

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  # PUT /posts/1/approve
  def approve
    @post = Post.find(params[:id])
    @post.approved = true
    @post.reviewed = true
    if @post.save
      # FIXME: Figure out why notice isn't appearing
      # redirect_to action: 'review', notice: 'Post was successfully approved.'
      redirect_to action: 'review'
    else
      redirect_to action: 'review'
    end
  end

  # PUT /posts/1/disapprove
  def disapprove
    @post = Post.find(params[:id])
    @post.approved = false
    @post.reviewed = true
    if @post.save
      # FIXME: Figure out why notice isn't appearing
      # redirect_to action: 'review', notice: 'Post was successfully disapproved.'
      redirect_to action: 'review'
    else
      redirect_to action: 'review'
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    @votes = session[:votes]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    if is_admin?
      @post = Post.find(params[:id])
    else
      redirect_to root_url
    end
  end

  # POST /posts
  def create
    type = params[:post][:type]
    if type == 'FML'
      @post = FML.new(params[:post])
    elsif type == 'Meme'
      @post = Meme.new(params[:post])
    elsif type == 'GIF'
      @post = GIF.new(params[:post])
    end
    @post.ip = request.remote_ip

    if @post.save
      redirect_to root_url, notice: 'Thanks for submitting! Your post should appear soon.'
    else
      @posts = Post.approved.recent.paginate(page: params[:page], per_page: 20)
      render 'index'
    end
  end

  # POST /posts/sms
  def sms
    @post = FML.new
    @post.content = params[:Body]
    if @post.save
      render text: 'Thanks for submitting! Your post should appear soon.', content_type: Mime::TEXT
    else
      render text: @post.errors.full_messages.join, content_type: Mime::TEXT
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        # FIXME: Notice does not display for some reason
        # format.html { redirect_to action: "review", notice: 'Post was successfully updated.' }
        if @post.approved
          format.html { redirect_to review_path(view: 'approved') }
        else
          format.html { redirect_to review_path }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to action: "review" }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:post_id])

    # FIXME: Uncomment
    # Check that user has not already voted for this post
    # @votes = session[:votes]
    # if @votes.nil? or not @votes.include? @post.id
      @post.likes += 1
      @post.save

      if session[:votes].nil?
        session[:votes] = Set.new([@post.id])
      else
        session[:votes].add(@post.id)
      end
    # end

    render json: @post.likes
  end

  def downvote
    @post = Post.find(params[:post_id])

    # FIXME: Uncomment
    # Check that user has not already voted for this post
    # @votes = session[:votes]
    # if true or @votes.nil? or not @votes.include? @post.id
      @post.dislikes += 1
      @post.save

      if session[:votes].nil?
        session[:votes] = Set.new([@post.id])
      else
        session[:votes].add(@post.id)
      end
    # end

    render json: @post.dislikes
  end

  private

  def set_as_admin
    session[:admin] = true
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == 'dk' && password == 'twiliorocks' or
      username == 'pearlman' && password == 'pearlman'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if params[:action] == 'show' %>
  <% post = Post.new %>
<% else %>
  <% post = @post %>
<% end %>

<% if post.errors.any? %>
  <div class="error well">
    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="<%= 'active' if post.type.blank? or post.type == "FML" %>"><a href="#tab1" data-toggle="tab">FML</a></li>
    <li class="<%= 'active' if post.type == "Meme" %>"><a href="#tab2" data-toggle="tab">Meme</a></li>
    <li class="<%= 'active' if post.type == "GIF" %>"><a href="#tab3" data-toggle="tab">GIF</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane <%= 'active' if post.type.blank? or post.type == "FML" %>" id="tab1">
      <%= render partial: 'fmls/form', locals: { post: post } %>
    </div>
    <div class="tab-pane <%= 'active' if post.type == "Meme" %>" id="tab2">
      <%= render partial: 'memes/form', locals: { post: post } %>
    </div>
    <div class="tab-pane <%= 'active' if post.type == "GIF" %>" id="tab3">
      <%= render partial: 'gifs/form', locals: { post: post } %>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="post span8 well" data-target="<%= post.id %>">
  <div class="row">
    <div class="content span6 well <%= 'mod' if post.admin %>">
      <%= simple_format auto_link post.content %>
    </div>
    <div class="span2">
      <div class="meta center">
        <%= link_to post.created_at.strftime("%I:%M%p on %m/%d/%Y"), post_path(post), class: 'timestamp' %>
        <div class="vote">
          <a class="like btn btn-success <%= 'disabled' if @votes and @votes.include? post.id %>">
            <span class="count"><%= post.likes %></span>
            <i class="icon-thumbs-up"></i>
          </a>
          <a class="dislike btn btn-danger <%= 'disabled' if @votes and @votes.include? post.id %>">
            <span class="count"><%= post.dislikes %></span>
            <i class="icon-thumbs-down"></i>
          </a>
        </div>
        <%= link_to 'Post Comment', '#', class: 'post-comment' %>
      </div>
    </div>
  </div>

  <ul class="comments">
    <% unless post.comments.empty? %>
      <%= render partial: 'comments/comment', collection: post.comments %>
    <% end %>
  </ul>
</div>

app/views/posts/edit.html.erb
<% if @post.errors.any? %>
  <div class="error well span6">
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { class: 'well form-horizontal span8' } do |f| %>

  <div class="control-group">
    <%= f.label :content, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, rows: 2, class: 'content-field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :admin, class: 'control-label' %>
    <div class="controls">
      <%= f.check_box :admin, class: 'admin-field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Submit", class: 'btn btn-primary submit-comment' %>
    <button class="btn cancel-comment">Cancel</button>
  </div>
  <div class="links">
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', action: 'review' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <div class="sidebar span3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="offset3 span9">
    <div class="posts row">
      <%= render @posts %>
    </div>

    <div class="new-comment" style="display: none;">
      <%= render partial: 'comments/form' %>
    </div>

    <%= will_paginate class: 'pagination center', page_links: false %>
    <div class="load-status center"></div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/review.html.erb
<% if notice %>
<div class="notice well span6">
  <%= notice %>
</div>
<% end %>

<p>
  <% if request.url != review_url %>
  <%= link_to 'Unreviewed Posts', review_path, class: 'btn btn-info' %>
  <% elsif request.url != review_url(view: 'approved') %>
  <%= link_to 'Approved Posts', review_path(view: 'approved'), class: 'btn btn-success' %>
  <% end %>
</p>

<table class="table" style="background-color: #FFF; table-layout: fixed">
  <thead>
    <tr>
      <th>Approved</th>
      <th>IP</th>
      <th>Image</th>
      <th>Content</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
        <% if post.approved %>
      <tr class="approved">
          <td><i class="icon-ok"></i></td>
        <% else %>
      <tr class="unapproved">
          <td><i class="icon-remove"></i></td>
        <% end %>
        <td><%= post.ip %></td>
        <td><%= image_tag post.image.url(:original) unless post.image_file_name.blank? %></td>
        <td class="<%= 'mod' if post.admin %>"><%= simple_format auto_link h post.content %></td>
        <td><%= post.created_at.strftime("%I:%M%p %m/%d/%Y") %></td>
        <td>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn' %>
          <%= link_to 'Deny', disapprove_post_path(post), class: 'btn btn-danger', method: :put %>
          <%= link_to 'Approve', approve_post_path(post), class: 'btn btn-primary', method: :put %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate class: 'pagination center' %>

app/views/posts/show.html.erb
<div class="row">
  <div class="sidebar span3">
    <%= render 'layouts/sidebar' %>
  </div>

  <div class="offset3 span9">
    <div class="posts row">
      <p id="notice"><%= notice %></p>
      <%= render @post %>
    </div>

    <div class="new-comment" style="display: none;">
      <%= render partial: 'comments/form' %>
    </div>
  </div>
</div>