config/routes.rb
Ptonfml::Application.routes.draw do
  resources :posts, except: :new

  match 'posts/sms', to: 'posts#sms', via: 'post'

  match 'liked', to: 'posts#liked', as: :most_liked
  match 'disliked', to: 'posts#disliked', as: :most_disliked

  match 'search', to: 'posts#search', as: :search

  resources :comments, only: [:create, :destroy]

  match 'review', to: 'posts#review', as: :review

  match 'posts/:id/approve', to: 'posts#approve', via: 'put', as: :approve_post
  match 'posts/:id/disapprove', to: 'posts#disapprove', via: 'put', as: :disapprove_post

  match 'posts/upvote', to: 'posts#upvote', via: 'post'
  match 'posts/downvote', to: 'posts#downvote', via: 'post'

  root to: 'posts#index'

end

app/views/layouts/_ga.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31857094-1']);
  _gaq.push(['_trackPageview']);

  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <%= link_to "PrincetonFML", root_url, class: "brand", id: "logo" %>

      <div class="nav-collapse">
        <ul class="nav">
          <li class="<%= 'active' if request.url == root_url %>">
            <%= link_to "Most Recent", root_url %>
          </li>
          <li class="<%= 'active' if request.url == most_liked_url %>">
            <%= link_to "Most Liked", most_liked_url %>
          </li>
          <li class="<%= 'active' if request.url == most_disliked_url %>">
            <%= link_to "Most Disliked", most_disliked_url %>
          </li>
        </ul>
        <form class="navbar-search pull-right" action="<%= search_path %>">
          <input type="text" name="query" class="search-query" placeholder="Search FMLs" value="<%= params[:query] %>">
        </form>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="well center sms">
  <h2>Text your FML<br /><span class="phone-number">(609) 751-9571</span></h2>
</div>

<div class="well">
  <% if notice %>
    <div class="notice well">
      <%= notice %>
    </div>
  <% end %>

  <%= render 'posts/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="PrincetonFML">
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

  <% if Rails.env.production? %>
    <%= render 'layouts/ga' %>
  <% end %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>